export { default as InstanceTree } from './InstanceTree.vue'
export { default as IconSettings } from './IconSettings.vue'
export { default as IconPicker } from './IconPicker.vue'
export { default as ViewsPanel } from './ViewsPanel.vue'
export { default as ViewsEditorDialog } from './ViewsEditorDialog.vue'
export { default as ViewsEditorPanel } from './ViewsEditorPanel.vue'
